kind: Deployment
apiVersion: apps/v1
metadata:
  name: steamcmd-gmod
  namespace: ryan-test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: steamcmd-gmod
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: steamcmd-gmod
    spec:
      volumes:
        - name: gmod-volume
          persistentVolumeClaim:
            claimName: gmod-volume
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: container
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: gmod-volume
              mountPath: /data
          terminationMessagePolicy: File
          image: 'steamcmd/steamcmd:latest'
          args:
            - +force_install_dir
            - /data
            - +login
            - anonymous
            - +app_update
            - '4020'
            - +quit
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
